[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts=lib/chainlink/contracts/src/v0.6/",
    "@openzeppelin/contracts=lib/openzeppelin/contracts/contracts/",
]
solc = "0.8.18"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
